# Generated by Django 5.2.9 on 2025-12-25 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='полное имя')),
                ('birth_date', models.DateField(verbose_name='дата рождения')),
                ('passport', models.CharField(max_length=20, unique=True, verbose_name='номер паспорта')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма вклада')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='процентная ставка')),
                ('term_months', models.IntegerField(verbose_name='срок в месяцах')),
                ('start_date', models.DateField(verbose_name='дата начала')),
                ('status', models.CharField(choices=[('active', 'активен'), ('closed', 'закрыт')], default='active', max_length=20, verbose_name='статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='bank_api.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'вклад',
                'verbose_name_plural': 'вклады',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма кредита')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='процентная ставка')),
                ('term_months', models.IntegerField(verbose_name='срок в месяцах')),
                ('start_date', models.DateField(verbose_name='дата начала')),
                ('status', models.CharField(choices=[('active', 'активен'), ('paid', 'погашен'), ('overdue', 'просрочен')], default='active', max_length=20, verbose_name='статус')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ежемесячный платеж')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='bank_api.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'кредит',
                'verbose_name_plural': 'кредиты',
            },
        ),
    ]
